services:
  web:
    build:
      context: images/php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./www:/var/www
    networks:
      - lytko-crm-bot

  proxy:
    build:
      context: images/proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-80}:80
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./www/public:/var/www/public
      - ./images/proxy:/etc/nginx/conf.d/
    networks:
      - lytko-crm-bot

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    networks:
      - lytko-crm-bot

  ngrok:
    build:
      context: images/ngrok
      args:
        NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
        WEB_PORT: proxy:80
        NGROK_DOMAIN: ${NGROK_DOMAIN}
    restart: no
    container_name: ngrok
    ports:
      - "4040:4040"
    depends_on:
      - proxy
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    networks:
      - lytko-crm-bot

  db:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_USER:-login}
    volumes:
      - dbdata:/var/lib/postgres
    networks:
      - lytko-crm-bot

volumes:
  dbdata:
    driver: local

networks:
  lytko-crm-bot:
    driver: bridge